language: python
dist: xenial
sudo: true

python:
  - 3.8

services:
  postgresql
addons:
  postgresql: '9.5'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VETUALENVS=1
install:
 - pip install pipenv
 - pipenv sync -d
 script:
 - pipenv run flake8